### ISSUE TITLE
Pretrained model / weights?

### ISSUE THREAD

**Issue by MNoichl** [jin530/MelBERT#2]
I think this approach looks very promising, and I would like to try it out for a project that makes use of metaphor detection. I don't have access to the hardware necessary to run the training though.
Could you please make a pre-trained model available in some way? That would be super helpful for me!
Thank you!

Best,
Max

**Comment by jin530** [comment]
We will try to share it as soon as possible. :)

**Comment by skleee** [comment]
Sorry for being late. You can download a pre-trained MelBERT model checkpoint from the following link. The model is trained on VUA-18 dataset.
[https://drive.google.com/file/d/1RKyP-_kje6xWlNuXeoSIHZnYxUyXnupZ/view?usp=sharing](https://drive.google.com/file/d/1RKyP-_kje6xWlNuXeoSIHZnYxUyXnupZ/view?usp=sharing)
(updated on Feb 16, 2023)
