### ISSUE TITLE
A quick question please, what exactly is the training corpus "VUAall"?

### ISSUE THREAD

**Issue by liyucheng09** [jin530/MelBERT#3]
As far as I knew, VUA 20 contains all training instances, including VUA18, VUA-verb, VUA-genres. So while I saw the config file said the training file is VUAall, I am a little bit confused.

Thanks for any response.

**Comment by jin530** [comment]
Sorry for confusing you. Just ignore it. (VUAall is an old name for VUA18 inside our team.)

It would be good to refer to google drive for sharing data. 
https://drive.google.com/file/d/1738aqFObjfcOg2O7knrELmUHulNhoqRz/view?usp=sharing
