### ISSUE TITLE
How is the two-tailed t-test done

### ISSUE THREAD

**Issue by lzxlin** [jin530/MelBERT#4]
Ask a question please, how is the two-tailed t-test done, thanks a lot.

**Comment by jin530** [comment]
Hello, thank you so much for being interested.

Each model was run five times with different random seeds, and a two-tailed t-test was performed based on it.

**Comment by lzxlin** [comment]
thank you for your reply, so the baselines also need to be run five times？



---Original---
From: "Minjin ***@***.***&gt;
Date: Sun, Nov 7, 2021 14:22 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [jin530/MelBERT] How is the two-tailed t-test done (Issue #4)




 
Hello, thank you so much for being interested.
 
Each model was run five times with different random seeds, and a two-tailed t-test was performed based on it.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jin530** [comment]
Yes.
Because of the variance, we also ran the baselines five times.
